<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Promise demo模拟</title>
</head>
<body>
<script>
    // 木有错误的情况下
    // 事务1 ( resolved )  完成了 执行事务2 ( pending )
    // 事务2 ( resolved )  完成了 执行事务3 ( pending )

    // 有错误的情况下
    // 事务1 ( 错误了 ) 于是后面的都干不了所有后面的全都变成rejected ( reeson信息异常捕获 )
    /**
     doFn1(function(data1){
        doFn2(function(data2){
            doFn3(function(data2){
            })
        })
     })
     */
    (function(){
        window.Promise = window.Promise || Promise;
        function Promise(){
            this.state = 'pending';
        }
        Promise.prototype.constructor = Promise;
        Promise.prototype.then = function(){
            var promise = new Promise();
            if(this.state == 'resolved'){
            }else{

            }
        }
    })();
</script>
</body>
</html>